name: Build Docker Image
on:
  - push
jobs:
  build-image:
    name: Build and --- wait, where's the push step? WHO FORGOT THE PUSH STEP?
    runs-on: ubuntu-latest
    steps:
      - name: Make repository contents available on the runner
        uses: actions/checkout@v4

      - name: Build the image
        run: docker build -t httpd-practice:latest .
