name: deploy-new-image
on:
  workflow_run:
    workflows: [ "build-and-push" ]
    types: [ completed ]
jobs:
  authenticate-to-aws:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Copnfigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Verify AWS identity
        run: aws sts get-caller-identity