name: deploy-new-image
on:
  workflow_run:
    workflows: [ "build-and-push" ]
    types: [ completed ]

# For Free GitHub accounts, gating job execution behind environment approval is not supported for private repositories.
# This repository needs to be public for that.
jobs:
  authenticate-to-aws:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Verify AWS identity
        run: aws sts get-caller-identity
        # The next step is only useful if we are pushing our image to ECR.
        # We would need to build and tag the artifact in this workflow to push it to ECR.
        # The "Login to ECR" becomes useless if we store our images in a public Docker registry.
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 |
          docker login --username AWS --password-stdin 881197861415.dkr.ecr.ap-southeast-2.amazonaws.com
        # From hereonout, we can push our image to ECR and / or update the relevant ECS service.
      - name: Force new deployment on the ECS service
        run: |
          aws ecs update-service --cluster WebsiteCluster --service httpd-practice-service \
          --force-new-deployment
